import React, { useCallback, useState } from 'react'
import { Badge } from './ui/badge'
import { AlertCircleIcon, Sparkle } from 'lucide-react'
import { Button } from './ui/button'
import { Gemini } from './ui/svgs/gemini'
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"
import { Alert, AlertDescription, AlertTitle } from './ui/alert'
import { Spinner } from './ui/spinner'
import useAxiosMod from '@/hooks/useAxiosMod'
import toast from 'react-hot-toast'
// import { useAppSelector } from '@/store/hooks'


type Summary = {
  title: string;
  content: string;
  suggested_topics: [string]
}

function AISummary({ content }: { content: string }): React.ReactNode {


  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState(null)
  const axiosAuth = useAxiosMod();
  const [summary, setSummary] = useState<Summary | null>(null);

  // const { status } = useAppSelector(state => state.auth)

  const fetchAISummary = useCallback(async () => {


    setLoading(true);
    try {

      const res = await axiosAuth.post("/api/ai/summary", {
        content
      });
      setSummary(res.data);
      toast.success("Summary Generated")



    } catch (error) {
      toast.error("Failed to Generate Summary")
      setError(error)
      console.log(error)
    } finally {
      setLoading(false)
    }
  }, [axiosAuth, content, setError]);


  return (
    <div className="px-10 sm:mt-10 py-5 flex flex-col gap-4">
      <Badge className="flex items-center px-3 py-1">
        <Sparkle />
        <span> AI Summary</span>

      </Badge>

      <Sheet>
        <SheetTrigger>
          <Button variant='default' className=' inline-flex px-6 '
            disabled={loading}
            onClick={() => {
              fetchAISummary();
            }}
          >
            {/* Invisible text keeps width */}
            <span className={loading ? "invisible" : "visible"}>
              Summary with Gemini
            </span>

            {/* Gemini icon (always present) */}
            <Gemini className={loading ? "invisible h-4 w-4" : "h-4 w-4"} />

            {/* Spinner overlays when loading */}
            {loading && (
              <span className="absolute flex items-center gap-2">
                <Spinner />
                <Gemini className="h-4 w-4" />
              </span>
            )}
          </Button>
        </SheetTrigger>
        <SheetContent side='left' className="w-full px-5 py-5 sm:w-96 overflow-y-auto">
          <SheetHeader className="mb-6">
            <SheetTitle className="flex items-center gap-2 text-lg">
              <Gemini className='w-6' />
              Gemini Generated Summary
            </SheetTitle>
          </SheetHeader>
          <SheetDescription className=''>
            <Badge>Powered by Gemini 2.5 Pro</Badge>
          </SheetDescription>

          {
            (!loading && summary && summary.content) ? (

              <div className=''>
                <Alert variant="default">
                  <AlertTitle>Summary</AlertTitle>
                  <AlertDescription className='flex flex-col gap-5'>
                    <div>
                      <h2 className='font-semibold'> {summary.title} </h2>
                      <p> {summary.content} </p>
                    </div>
                    <div className='flex flex-col gap-3'>
                      <h1 className='font-semibold'>Tags</h1>

                      {
                        summary && summary.suggested_topics != null && summary.suggested_topics.map(item => {
                          return <Badge className='px-2' variant='outline'> {item} </Badge>
                        })
                      }

                    </div>

                  </AlertDescription>
                </Alert>

              </div>
            ) : (

              <div className='w-full flex-1 border-dashed border-2 rounded-lg flex items-center justify-center'>
                <Spinner className='size-6' />
              </div>
            )
          }

          <Alert variant="default">
            <AlertCircleIcon />
            <AlertTitle>Please Note</AlertTitle>
            <AlertDescription className='flex flex-col gap-5'>
              <p>This summary was generated by AI and may not capture all nuances of the original article.
                Please read the full article for complete understanding.</p>



            </AlertDescription>
          </Alert>
        </SheetContent>
      </Sheet>
    </div>
  )
}

export default AISummary